# File: .github/workflows/hugo.yml
name: Deploy Hugo Site to Pages

on:
  push:
    branches:
      - main  # Hoặc 'master' nếu nhánh chính của bạn tên là master

# Cấp quyền cho GITHUB_TOKEN để deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ chạy một lần deploy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: true

# Cấu hình môi trường mặc định
defaults:
  run:
    shell: bash

jobs:
  # Bước 1: Build trang web
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0 # Hoặc phiên bản Hugo bạn đang dùng
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Bước 2: Deploy lên GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4